config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sogn_out: 'logout', sign_up: 'register' }

  root to: 'pages#home'
  
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do 
    member do 
      post :toggle_status
    end
  end
  
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord  
  # Validations
  include Placeholder

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  #Associations
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda {|attr| attr["name"].blank?}

  validates_presence_of :title, :subtitle, :body

  # Scopes
  scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails") }
  scope :order_by_position, -> { order("position ASC") }

  def self.angular
    where(subtitle: "Angular")
  end
  
  # Callbacks
  # after_initialize :set_default_image

  # def set_default_image
  #   self.main_image ||= Placeholder.image_generator(width: 600, hieght: 400)
  #   self.thumb_image ||= Placeholder.image_generator(width: 350, hieght: 200)
  # end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  access all: [:show, :index, :angular], user: {except: [:destroy, :edit, :update, :new, :create, :destroy, :sort]}, site_admin: :all
  layout "portfolio"  
  
  def index
    @portfolio_items = Portfolio.all.order_by_position
  end

  def sort 
    params['order'].each do |key, value|
      Portfolio.find_by(id: value['id']).update(position: value['position'])
    end
    render body: nil
  end

  def angular
    @angular_portfolio = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build }
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio = Portfolio.find_by(id: params[:id])
    3.times { @portfolio.technologies.build } unless @portfolio.technologies.present?
  end

  def update
    @portfolio = Portfolio.find_by(id: params[:id])
    if @portfolio.update(portfolio_params)
      redirect_to portfolios_path, notice: "Record updated successfully"
    else
      render :edit
    end
  end

  def show
    @portfolio = Portfolio.find_by(id: params[:id])
  end

  def destroy
    @portfolio = Portfolio.find_by(id: params[:id])
    @portfolio.destroy
    redirect_to portfolios_path, notice: 'Portfolio was successfully deleted.'
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:id, :name])  
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_area :subtitle, class: "form-control" %>
      </div>

       <div class="form-group">
        <%= form.label :main_image %>
        <%= form.file_field :main_image %>
      </div>

       <div class="form-group">
        <%= form.label :thumb_image %>
        <%= form.file_field :thumb_image %>
      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 11 %>
      </div>
    </div>
  </div>
  <h3>Technologies Used</h3>
  <hr>
  <div>
    <%= form.fields_for :technologies do |tech| %>
    <div class="form-group">
      <%= tech.label :name %>
      <%= tech.text_field :name, class: "form-control" %>
    </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Save Portfolio", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_item.thumb_image.present? ? portfolio_item.thumb_image.url : Placeholder.image_generator(width: 350, hieght: 200), height: 200 %>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio</h1>
<%= link_to "New Portfolio", new_portfolio_path %>
<% @angular_portfolio.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image if portfolio_item.thumb_image.present? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to "Delete Portfolio", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container">
  <h1>Edit the Portfolio</h1>
  <%= render "form", portfolio: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<h1>Portfolio Index</h1>
<%#= link_to "New Portfolio", new_portfolio_path if logged_in?(:site_admin) %>
<div class="row <%= "sortable" if logged_in?(:site_admin)  %>">
  <%= render partial: "portfolio_item", collection: @portfolio_items %>
</div>


<script type="text/javascript">

var ready, set_positions;

set_positions = function() {
  $('.card').each(function(i) {
    $(this).attr('data-pos', i + 1);
  });
};

ready = function() {
  set_positions();
  $('.sortable').sortable();
  $('.sortable').sortable().bind('sortupdate', function(e, ui) {
    var updated_order = [];
    set_positions();
    
    $('.card').each(function(i) {
      updated_order.push({
        id: $(this).data('id'),
        position: i + 1
      });
    });
    
    $.ajax({
      type: 'PUT',
      url: '/portfolios/sort',
      data: { order: updated_order }
    });

  });
};

$(document).ready(ready);

</script>

app/views/portfolios/new.html.erb
<div class="container">
  <h1>Create new Portfolio</h1>
  <%= render "form", portfolio: @portfolio %>  
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7"> 
      <%= image_tag @portfolio.main_image.present? ? @portfolio.main_image.url : Placeholder.image_generator(width: 600, hieght: 400), width: 600 %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio.title %></h1>
      <em><%= @portfolio.subtitle %></em>
      <p><%= @portfolio.body %></p>
      <h3>Added technologies</h3>
      <% @portfolio.technologies.each do |tech| %>
        <%= tech.name %>
      <% end %>
    </div>
  </div>
</div>