config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sogn_out: 'logout', sign_up: 'register' }

  root to: 'pages#home'
  
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do 
    member do 
      post :toggle_status
    end
  end
  
end

app/views/shared/_application_copyright.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner app-footer">
    <p style="text-align: center;"><%= copyright_message %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Umesh Kushwaha</h3>
    <nav class="nav nav-masthead justify-content-center main-nav-items">
     <%= nav_items("nav-link", "span") %>
      <%= header_links("nav-link") %>
    </nav>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav bg-light">
      <%= nav_items("nav-link", "span") %>
      <%= header_links 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  
  <div class="card">
    <div class="card-body bg-light text-muted">
      <h5>About</h5>
      <p>
        Hi, I am a 3 year experienced Ruby on Rails developer. I love to code because after doing coding I get pay for it and if you want to survive you must need money.
      </p>
    </div>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-link">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
  <div class="<%= location %>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "About", about_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "Blogs", blogs_path %></div>
    <div><%= link_to "Portfolios", portfolios_path %></div>
  </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "All Portfolios", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_message %></p>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">My Profile</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_items("text-white", "li") %>
            <li><%= header_links 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <span style="font-size: 20px;"><%= fa_icon "user-circle" %></span>&nbsp
        <strong>Umesh Kushwaha</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_portfolio_heading.html.erb
<% unless logged_in?(:site_admin) %>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">About me</h1>
      <p class="lead text-muted">Hi, I am 2.5 year experienced Ruby on Rails developer, currently I am working as a freelancer but I am looking for the full time work as a ROR developer.</p>
      <p>
        <%= link_to "More About Me", about_path, class: "btn btn-primary my-2" %>
        <%= link_to "Blog", blogs_path, class: "btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
<% end %>